### ISSUE TITLE
Flashbots Protect RPC for Sepolia

### ISSUE THREAD

**Issue by michalinacienciala** [flashbots/rpc-endpoint#126]
Hi, I found [here](https://github.com/flashbots/flashbots-docs/blob/main/docs/flashbots-protect/quick-start.mdx#L56C1-L60C55) information about Flashbots Protect Goerli RPC. As Goerli testnet is getting deprecated with end of 2023, are there any plans to support RPC for Sepolia?

**Comment by zach030** [comment]
sepolia is alive on https://relay-sepolia.flashbots.net

**Comment by sukoneck** [comment]
that doc has been updated since you asked. now it says:

> Below is the list of Flashbots Protect RPCs we currently support across the Ethereum mainnet and testnets:

| Network  | URL                                      |
| -------- | ---------------------------------------- |
| Mainnet  | `https://rpc.flashbots.net`              |
| Goerli   | `https://rpc-goerli.flashbots.net`       |
| Sepolia  | `https://rpc-sepolia.flashbots.net`      |
| Holesky  | `https://rpc-holesky.flashbots.net`      |
